#%RAML 0.8
title: Case Management Query API
baseUri: http://localhost:8080/stagingprosecutorscivil-query-api/query/api/rest/stagingprosecutors-civil
protocols: [ HTTP, HTTPS ]

/submissions/{submissionId}:
  get:
    description: |
      Gets the Civil Prosecution submission details
      ...
      (mapping):
        responseType: application/vnd.stagingprosecutorscivil.submission-details+json
        name: stagingprosecutorscivil.submission-details
      (mapping):
        responseType: text/csv
        name: stagingprosecutorscivil.submission-error-details-csv
      ...
    queryParameters:
      additionalInfo:
        description: when true, also returns fileName, username and prosecutingAuthority captured from the complaints CSV upload, when present on the submission
        type: boolean
        default: false
    responses:
        200:
          description: OK
          body:
            application/vnd.stagingprosecutorscivil.submission-details+json:
              example:  !include json/stagingprosecutorscivil.submission-details.json
              schema:  !include json/schema/stagingprosecutorscivil.submission-details.json
            text/csv:

/complaints-files-template:
  get:
    description: |
      Retrieve the complaints files CSV template.
      ...
      (mapping):
        responseType: text/csv
        name: stagingprosecutorscivil.complaints-files-template
      ...
    responses:
        200:
          description: OK
          body:
            text/csv: