package uk.gov.moj.cpp.staging.civil.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.staging.civil.handler.command.api.accesscontrol.RuleConstants;
global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for Others Prosecution"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingcivil.other-case");
    eval(userAndGroupProvider.hasPermission($action, RuleConstants.getCivilCasePermission()));
  then
    $outcome.setSuccess(true);
end

rule "Command - Rule for Summons Prosecution"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingcivil.summons");
    eval(userAndGroupProvider.hasPermission($action, RuleConstants.getCivilCasePermission()));
  then
    $outcome.setSuccess(true);
end