#%RAML 0.8
title: Prosecutors Command handler
version: 1.0
baseUri: message://command/handler/message/stagingprosecutors-civil

/stagingprosecutorscivil.handler.command:
    post:
      description: |
        Receives a request

      body:
         application/vnd.stagingcivil.command.other-case+json:
             schema: !include json/schema/stagingcivil.command.other-case.json
             example: !include json/stagingcivil.command.other-case.json
         application/vnd.stagingcivil.command.summons+json:
             schema: !include json/schema/stagingcivil.command.summons.json
             example: !include json/stagingcivil.command.summons.json
         application/vnd.stagingcivil.command.update-civil-case+json:
             schema: !include json/schema/stagingcivil.command.update-civil-case.json
             example: !include json/stagingcivil.command.update-civil-case.json
         application/vnd.stagingprosecutorscivil.command.submit-material+json:
             schema: !include json/schema/stagingprosecutorscivil.command.submit-material.json
             example: !include json/stagingprosecutorscivil.command.submit-material.json
         application/vnd.stagingprosecutorscivil.command.reject-material+json:
             schema: !include json/schema/stagingprosecutorscivil.command.reject-material.json
             example: !include json/stagingprosecutorscivil.command.reject-material.json
         application/vnd.stagingprosecutorscivil.command.receive-material-submission-successful+json:
             schema: !include json/schema/stagingprosecutorscivil.command.receive-material-submission-successful.json
             example: !include json/stagingprosecutorscivil.command.receive-material-submission-successful.json
