  #%RAML 0.8
title: Case Management Command API
version: 1.0
baseUri:  http://localhost:8080/stagingprosecutorscivil-command-api/command/api/rest/staging-civil

/cases:
  post:
      description:  |
        Submit civil prosecutions
        ...
        (mapping):
            requestType: application/vnd.stagingcivil.other-case+json
            name: stagingcivil.other-case
        (mapping):
            requestType: application/vnd.stagingcivil.summons+json
            name: stagingcivil.summons
        ...
      body:
        application/vnd.stagingcivil.other-case+json:
          schema: !include json/schema/stagingcivil.other-case.json
          example: !include json/stagingcivil.other-case.json
        application/vnd.stagingcivil.summons+json:
          schema: !include json/schema/stagingcivil.summons.json
          example: !include json/stagingcivil.summons.json
      responses:
            202:
                description: OK
                body:
                  application/json:
                    schema: !include json/schema/stagingcivil.url-response.json
                    example: !include json/stagingcivil.url-response.json
            500:
                description: Internal Server Error